From openjdk:alpine AS builder
copy ./target/spring-boot-starter-amqp-0.0.1-SNAPSHOT.jar spring-boot-starter-amqp-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","spring-boot-starter-amqp-0.0.1-SNAPSHOT.jar"]
