server:
  port: 8073
spring:
  application:
    name: order-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
  security:
    basic:
      enable: false
    ignored: /**
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://sql-order-pod:3306/orderdb?createDatabaseIfNotExist=true&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

orderqueue:
  rabbitmq:
    exchange: order.exchange
    queue: order.queue
    routingkey: order.routingkey

cartqueue:
  rabbitmq:
    exchange: cart.exchange
    queue: cart.queue
    routingkey: cart.routingkey

